apiVersion: apps/v1
kind: Deployment
metadata:
  name: redditClone
spec:
  selector:
    matchLabels:
      app: reddit-clone
  template:
    metadata:
      labels:
        app: reddit-clone
    spec:
      containers:
      - name: reddit
        image: udiscopotato/redditclone
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: redditClone-svc
spec:
  selector:
    app: reddit-clone
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer

